CREATE DATABASE PROYECTOFINAL;

CREATE TABLE UNIDAD_MEDIDA (
    ID_UNIDAD INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_DE_UNIDAD VARCHAR(50) NOT NULL,
    UNIDAD_DE_MEDIDA VARCHAR(50) NOT NULL
);


CREATE TABLE ALIMENTOS (
    ID_ALIMENTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_DEL_ALIMENTO VARCHAR(100) NOT NULL,
    ID_UNIDAD INT,
    CANTIDAD DECIMAL(10,2) NOT NULL,
    CALORIAS DECIMAL(10,2) NOT NULL,
    C_PROTEINAS DECIMAL(10,2) NOT NULL,
    C_GRASAS DECIMAL(10,2) NOT NULL,
    C_CARBOHIDRATOS DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_UNIDAD) REFERENCES UNIDAD_MEDIDA(ID_UNIDAD)
);


CREATE TABLE GRASAS (
    ID_ALIMENTO INT PRIMARY KEY,
    G_SATURADA DECIMAL(10,2) NULL,
    G_INSATURADA DECIMAL(10,2) NULL,
    G_TRANS DECIMAL(10,2) NULL,
    FOREIGN KEY (ID_ALIMENTO) REFERENCES ALIMENTOS(ID_ALIMENTO)
);

CREATE TABLE PROTEINAS (
    ID_ALIMENTO INT PRIMARY KEY,
    AMINOACIDOS DECIMAL(10,2) NULL,
    FOREIGN KEY (ID_ALIMENTO) REFERENCES ALIMENTOS(ID_ALIMENTO)
);

CREATE TABLE CARBOHIDRATOS (
    ID_ALIMENTO INT PRIMARY KEY,
    FIBRA DECIMAL(10,2) NULL,
    AZUCAR DECIMAL(10,2) NULL,
    FOREIGN KEY (ID_ALIMENTO) REFERENCES ALIMENTOS(ID_ALIMENTO)
);


CREATE TABLE FACTOR_ACTIVIDAD (
    ID_FACTOR INT PRIMARY KEY AUTO_INCREMENT,
    FACTOR_DE_ACTIVIDAD VARCHAR(50) NOT NULL,
    DESCRIPCION TEXT NULL,
    VALOR DECIMAL(5,2) NOT NULL
);

CREATE TABLE IMC (
    ID_IMC INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_CATEGORIA VARCHAR(50) NOT NULL,
    RANGO VARCHAR(20) NOT NULL
);

CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(50) NOT NULL,
    APELLIDO_DE_USUARIO VARCHAR(50) NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    CONTRASEÑA VARCHAR(100) NOT NULL,
    SEXO VARCHAR(10) NOT NULL,
    ALTURA DECIMAL(5,2) NOT NULL,
    PESO DECIMAL(5,2) NOT NULL,
    PESO_OBJETIVO DECIMAL(5,2) NOT NULL,
    IMC DECIMAL(5,2) NOT NULL,
    ID_FACTOR INT NOT NULL,
    CALORIAS_RECOMENDADAS DECIMAL(10,2) NOT NULL,
    ID_CATEGO_IMC INT NOT NULL,
    FOREIGN KEY (ID_FACTOR) REFERENCES FACTOR_ACTIVIDAD(ID_FACTOR),
    FOREIGN KEY (ID_CATEGO_IMC) REFERENCES IMC(ID_IMC)
);

CREATE TABLE CONSUMEN (
    ID_CONSUMO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_ALIMENTO INT NOT NULL,
    FECHA_CONSUMO DATE NOT NULL,
    CANTIDAD DECIMAL(10,2) NOT NULL,
    FIBRA_T DECIMAL(10,2) NULL,
    AZUCAR_T DECIMAL(10,2) NULL,
    AMINOACIDOS_T DECIMAL(10,2) NULL,
    G_SATURADA_T DECIMAL(10,2) NULL,
    G_INSATURADA_T DECIMAL(10,2) NULL,
    G_TRANS_T DECIMAL(10,2) NULL,
    CALORIAS_T DECIMAL(10,2) NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_ALIMENTO) REFERENCES ALIMENTOS(ID_ALIMENTO)
);

